/**
 * Database types — generated by `supabase gen types typescript`.
 *
 * TODO: run after the schema is applied:
 *   npx supabase gen types typescript --project-id vqrqygyfsrjpzkaxjleo > lib/supabase/types.ts
 *
 * For now, a permissive shape so the clients type-check.
 */
export type Database = {
  public: {
    Tables: Record<string, { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }>;
    Views: Record<string, { Row: Record<string, unknown> }>;
    Functions: Record<string, { Args: Record<string, unknown>; Returns: unknown }>;
    Enums: Record<string, string>;
  };
};
